#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import argparse
import sys
import os
import subprocess
import platform
import json

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def exitnagios(status,message):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

def oom_kernel_check(criticallevel, warninglevel, short=False):
    infomsg("KERNEL")

    cmdline = ["/usr/bin/journalctl","--utc","--no-pager","-kq","-o","json","-b","-0","--output-fields=MESSAGE"]
    infomsg(cmdline)
    completedproc = subprocess.run(cmdline,capture_output=True)
    output = completedproc.stdout.decode("utf-8").strip()
    errors = completedproc.stderr.decode("utf-8").strip()
    exitcode = completedproc.returncode

    #infomsg(output)

    logs = []
    if exitcode==0:
        counter=0
        for line in output.splitlines():
            try:
                parsed = json.loads(line)
                #infomsg(parsed)
                message = parsed["MESSAGE"]
                if "killed process" in message:
                    infomsg(parsed)
                    logs.append(message)
                    counter = counter+1
            except json.JSONDecodeError:
                continue

        return counter,logs
    else:
        return None,logs


def oom_systemd_check(criticallevel, warninglevel, short=False):
    infomsg("SYSTEMD")

    cmdline = ["/usr/bin/journalctl", "-u", "systemd-oomd.service", "--utc", "--no-pager", "-o", "json", "-b", "-0", "--output-fields=MESSAGE"]
    infomsg(cmdline)
    completedproc = subprocess.run(cmdline,capture_output=True)
    output = completedproc.stdout.decode("utf-8").strip()
    errors = completedproc.stderr.decode("utf-8").strip()
    exitcode = completedproc.returncode

    #infomsg(output)

    logs = []
    if exitcode==0:
        counter=0
        for line in output.splitlines():
            try:
                parsed = json.loads(line)
                #infomsg(parsed)
                message = parsed["MESSAGE"]
                if "Killed " in message:
                    infomsg(parsed)
                    logs.append(message)
                    counter += 1
            except json.JSONDecodeError:
                continue

        return counter,logs
    else:
        return None,logs

def oom_check(criticallevel, warninglevel, short=False):
    kernelcounter,kernellogs = oom_kernel_check(criticallevel, warninglevel, short)
    systemdcounter,systemdlogs = oom_systemd_check(criticallevel, warninglevel, short)

    if kernelcounter==None:
        exitnagios("CRITICAL","error retrieving the information from kernel oom journalctl | counter=-1")
    elif systemdcounter==None:
        exitnagios("CRITICAL","error retrieving the information from systemd oomd journalctl | counter=-1")
    else:
        counter = kernelcounter+systemdcounter
        logs = kernellogs+systemdlogs
        if criticallevel!="" and counter > int(criticallevel):
            exitnagios("CRITICAL",str(counter)+" processes was killed by OOM - "+str(logs)+" | counter="+str(counter))
        elif warninglevel!="" and counter > int(warninglevel):
            exitnagios("WARNING",str(counter)+" processes was killed by OOM - "+str(logs)+" | counter="+str(counter))
        else:
            exitnagios("OK","No OOM killer activity found | counter=-1")

#-------------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-w", "--warning",                                                          default="",                                   help="Number of occurences to trigger a warning")
    parser.add_argument("-c", "--critical",                                                         default="1",                                  help="Number of occurences to trigger a warning")
    parser.add_argument("-s", "--short",             action="store_true",                                                                         help="If this option is specified, check ignores dmesg OOM problems older then 24 hours")
    parser.add_argument("-®", "--debug",             action="store_true",  dest="debug",            default=False,                                help="be more verbose")
    args = parser.parse_args()

    setcandebug(args.debug)

    oom_check(args.critical, args.warning, args.short)

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    main()

#-------------------------------------------------------------------------------
