#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import sys
import os
import subprocess
import concurrent.futures
import argparse
import time

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def mapstatustoexitcode(status):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    return exitcode

def exitnagios(status,message):
    exitcode = mapstatustoexitcode(status)
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

def dosmstoolscall(modem):
    filename = "/var/log/smstools/smsd_stats/status"
    resultstatus = ""
    resultmsg = ""

    for counter in range(3):
        handle = None
        try:
            if os.path.isfile(filename):
                handle = open(filename, "r")
                contents = handle.read()
                for line in contents.splitlines():
                    infomsg(line)
                    if line.startswith(modem+":"):
                        infomsg("MATCHING -> "+line)
                        resultstatus = ""
                        resultmsg = ""
                        try:
                            parts = line.replace("\t"," ").split(": ",1)[1].split(", ")
                            infomsg("the parts are: ["+ ", ".join(parts)+"]")
                            status = parts[1].strip()
                            if status in ["Unknown"]:
                                infomsg("failing condition detected")
                                resultstatus = "CRITICAL"
                                resultmsg = "modem ID "+modem+" is not connected | signal=0"
                            else:
                                infomsg("doing deeper analysis")
                                if len(parts) > 5:
                                    info = parts[5].strip()
                                    blocks = info.split()
                                    signal = blocks[3].strip("(),")
                                    resultmsg = "modem ID "+modem+" is "+signal+" ("+blocks[1]+" dBm) | signal="+str(blocks[1])
                                    infomsg("the signal is "+signal)
                                    if signal in ["Excellent","Good","Workable"]:
                                        resultstatus = "OK"
                                    elif signal in ["Marginal"]:
                                        resultstatus = "WARNING"
                                    else:
                                        resultstatus = "CRITICAL"
                                else:
                                    infomsg("the line format is unknown")
                        except:
                            pass
        finally:
            if handle != None:
                handle.close()

        if resultmsg != "" and resultstatus != "":
            exitnagios(resultstatus,resultmsg)
        else:
            infomsg("sleeping...")
            time.sleep(5)

    exitnagios("CRITICAL","modem ID "+modem+" could not be parsed or is not defined | signal=0")

#-------------------------------------------------------------------------------

def main(forcedargs=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("-m", "--modem",                                   dest="modem",            default="",                                   help="modem ID")
    parser.add_argument("-®", "--debug",             action="store_true",  dest="debug",            default=False,                                help="be more verbose")
    args = parser.parse_args(forcedargs)

    setcandebug(args.debug)

    dosmstoolscall(args.modem)

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    main()

#-------------------------------------------------------------------------------
