#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import argparse
import sys
import os
import subprocess
import platform

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def exitnagios(status,message):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

def doospfroutescall():
    cmdline = ["/usr/bin/vtysh","-c","show ip route"]
    infomsg(cmdline)
    completedproc = subprocess.run(cmdline,capture_output=True)
    output = completedproc.stdout.decode("utf-8").strip()
    errors = completedproc.stderr.decode("utf-8").strip()
    exitcode = completedproc.returncode

    if exitcode == 0:
        total = 0
        for line in output.splitlines():
            if line.startswith("O") and ("is directly connected" not in line):
                total = total+1
                break
        if total>0:
            exitnagios("OK","there are remote OSPF routes | total="+str(total))
        else:
            exitnagios("CRITICAL","there are no remote OSFP routes | total="+str(total))
    else:
        exitnagios("CRITICAL","issue retrieving ospf routes | total="+str(total))

#-------------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-®", "--debug",             action="store_true",  dest="debug",            default=False,                                help="be more verbose")

    args = parser.parse_args()
    
    return args

def main():
    args = parse_args()
    setcandebug(args.debug)
    doospfroutescall()

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    main()

#-------------------------------------------------------------------------------
