#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import os
import sys
import subprocess
import re
import argparse

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def exitnagios(status,message):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

def checkgetent(verbose, database, key, value, partial):
    command = ['/usr/bin/getent', database]
    infomsg(line)
    if verbose:
        print(" ".join(command), flush=True)
    output = ""
    try:
        result = subprocess.check_output(command)
        output = result.decode('utf-8')
    except Exception as e:
        print("CRITICAL: exception during getent call", flush=True)
        return False

    if output == None:
        print("CRITICAL: no output from getent", flush=True)
        return False
    else:
        lines = output.splitlines()
        isok = False
        found = False
        for line in lines:
            infomsg(line)
            if  line.startswith(key+":"):
                found = True
                if ((value==None) or (value=="")):
                    print("OK: found key and no expected value was set - "+line, flush=True)
                    isok = True
                elif (line == key+value):
                    print("OK: found fully matching expected line "+line, flush=True)
                    isok = True
                elif partial and (line.startswith(key+value)):
                    print("OK: found partial match with expected line "+line, flush=True)
                    isok = True
                else:
                    print("CRITICAL: found unexpected line "+line+" but it was expected "+key+value, flush=True)
                break
        if found == False:
            print("CRITICAL: key not found "+key, flush=True)
        return isok

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-d", "--database",                       dest="database",                help="database to use (passwod, group, ...)")
    parser.add_argument("-k", "--key",                            dest="key",                     help="key to search")
    parser.add_argument("-l", "--value",                          dest="value",    default=None,  help="expected value")
    parser.add_argument("-p", "--partial",  action="store_true",  dest="partial",  default=False, help="is partial match")
    parser.add_argument("-w", "--warning",  action="store_false", dest="critical",                help="Return warning if not matching")
    parser.add_argument("-c", "--critical", action="store_true",  dest="critical", default=True,  help="Return critical if not matching (default)")
    parser.add_argument("-v", "--verbose",  action="store_true",  dest="verbose",                 help="Verbose operation")
    parser.add_argument("-q", "--quiet",    action="store_false", dest="verbose",                 help="Quiet operation")
    args = parser.parse_args()

    result = checkgetent(args.verbose, args.database, args.key, args.value, args.partial)
    if result == True:
        sys.exit(0)
    else:
        if args.critical:
            sys.exit(2)
        else:
            sys.exit(1)

if __name__ == '__main__':
    main()
