#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import os
import sys
import subprocess
import argparse
import mechanize
from bs4 import BeautifulSoup

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def exitnagios(status,message):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

def dotorcall(protocol,response):
    try:
        # https://check.torproject.org/api/ip
        url = "https://check.torproject.org/"
        br = mechanize.Browser()
        #proxyparts = proxy.split("://",1)
        #br.set_proxies({proxyparts[0]: proxyparts[1]})
        br.set_handle_robots(False) # ignore robots file
        #br.addheaders = [('User-agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)')]
        br.addheaders = [('User-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0')]
        res = br.open(url)
        content = res.read()
        if content == None:
            exitnagios("CRITICAL","no result from page")

        soup = BeautifulSoup(content, "html.parser")

        element = soup.find("h1")
        status = element["class"][0]
        if status==response:
            exitnagios("OK","the result '"+status+"' is as expected")
        else:
            exitnagios("CRITICAL","the result '"+status+"' is not the expected value '"+response+"'")

    except Exception as e:
        exitnagios("CRITICAL","unexpected error during the check "+str(e))

#-------------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-4", "--ipv4",              action="store_true",  dest="ipv4",             default=False,                                help="use ipv4 (default, exclusive with ipv6)")
    parser.add_argument("-6", "--ipv6",              action="store_true",  dest="ipv6",             default=False,                                help="use ipv6 (exclusive with ipv4)")
    #parser.add_argument("-p", "--proxy",                                   dest="proxy",            default="",                                   help="use a proxy")
    parser.add_argument("-r", "--response",                                dest="response",         default="open",                               help="respose: open,closed")
    parser.add_argument("-®", "--debug",             action="store_true",  dest="debug",            default=False,                                help="be more verbose")
    args = parser.parse_args()

    setcandebug(args.debug)

    if (args.ipv4 == True) and (args.ipv6 == True):
        exitnagios("CRITICAL","choose ipv4 or ipv6, not both")
    if (args.ipv4 == False) and (args.ipv6 == False):
        args.ipv4 = True
    #infomsg(args.ipv4)
    #infomsg(args.ipv6)

    protocol = ""
    if args.ipv4 == True :
        protocol = "-4"
    elif args.ipv6 == True :
        protocol = "-6"

    dotorcall(protocol,args.response)

if __name__ == '__main__':
    main()

#-------------------------------------------------------------------------------