#!/usr/bin/env python3
#-------------------------------------------------------------------------------

import os
import sys
import time
import subprocess
import argparse
import datetime
import dns.resolver
import asyncio

import nodriver as uc
#from fake_useragent import UserAgent

#-------------------------------------------------------------------------------

_candebug = False
def candebug():
    global _candebug
    return _candebug
def setcandebug(value):
    global _candebug
    _candebug = value

def infomsg(msg):
    if candebug() == True:
        print(msg, flush=True)

def mapstatustoexitcode(status):
    if status=="OK":
        exitcode = 0
    elif status=="WARNING":
        exitcode = 1
    elif status=="CRITICAL":
        exitcode = 2
    elif status=="UNKNOWN":
        exitcode = 3
    else:
        exitcode = 4
    return exitcode

def exitnagios(status,message):
    exitcode = mapstatustoexitcode(status)
    print(status+": "+message, flush=True)
    sys.exit(exitcode)

#-------------------------------------------------------------------------------

async def generatedriver(proxy):
    browserargs = []
    #browserargs.append("--incognito")
    #browserargs.append("--enable-features=EphemeralGuestProfilesOnStartup")
    browserargs.append("--disk-cache-size=0")
    browserargs.append("--media-cache-size=0")
    browserargs.append("--headless")
    browserargs.append("--disable-gpu")
    browserargs.append("--no-zygote")
    browserargs.append("--renderer-process-limit=1")
    browserargs.append("--no-sandbox")
    browserargs.append("--disable-dev-shm-usage")
    browserargs.append("--in-process-gpu")
    browserargs.append("--use-gl=angle")
    browserargs.append("--use-angle=swiftshader-webgl")
    browserargs.append("--disable-popup-blocking")
    if proxy not in ["", None]:
        browserargs.append("--proxy-server=" + proxy)
    #ua = UserAgent()
    #browserargs.append(f'user-agent={ua.random}')
    browserargs.append("--user-agent=\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.7204.298 Safari/537.36\"")
    browserconfig = uc.Config(browser_args=browserargs)

    driver = await uc.start(browserconfig)
    #driver.implicitly_Wait(10, TimeUnit.SECONDS)

    uc.cdp.network.enable()
    #uc.cdp.network.setExtraHTTPHeaders("Network.setExtraHTTPHeaders",{"headers": {"Accept-Language": "en-US,en;q=0.9","Sec-Fetch-Site": "none","Sec-Fetch-Mode": "navigate","Sec-Fetch-User": "?1","Sec-Fetch-Dest": "document"}})

    return driver

async def get_html_source(page):
    js = """
    (() => {
        return document.documentElement.outerHTML;
    })();
    """
    response, session = await page.send(uc.cdp.runtime.evaluate(expression=js, return_by_value=True))
    html = response.value
    return html

async def get_page_title(page):
    js = """
    (() => {
        return document.title;
    })();
    """
    response, session = await page.send(uc.cdp.runtime.evaluate(expression=js, return_by_value=True))
    title = response.value
    return title

async def check_page_loaded(page):
    js = """
    (() => {
        return document.readyState;
    })();
    """
    response, session = await page.send(uc.cdp.runtime.evaluate(expression=js, return_by_value=True))
    page_state_value = response.value
    infomsg("page state is '"+str(page_state_value)+"'")
    result = (page_state_value == "complete")
    return result

async def wait_page_loaded(page):
    timestamp = time.time()
    while True:
        loaded = await check_page_loaded(page)
        if loaded == True:
            break
        if time.time() - timestamp > 20:
            break
        time.sleep(1)

#-------------------------------------------------------------------------------

def tryfindbyxpath(driver,xpath):
    result = []
    try:
        result = driver.find_elements(By.XPATH, xpath)
    except:
        pass
    return result

def tryfindbyid(driver,idname):
    result = []
    try:
        result = driver.find_elements(By.ID, idname)
    except:
        pass
    return result

def tryfindbyclassname(driver,classname):
    result = []
    try:
        result = driver.find_elements(By.CLASS_NAME, classname)
    except:
        pass
    return result

def tryfindbytagname(driver,tagname):
    result = []
    try:
        result = driver.find_elements(By.TAG_NAME, tagname)
    except:
        pass
    return result

#-------------------------------------------------------------------------------

def resolverecord(protocol,hostname):
    result = []
    try:
        record = None
        if protocol in ["-4","4"]:
            record = "A"
        if protocol in ["-6","6"]:
            record = "AAAA"
        if record!=None:
            answers = dns.resolver.resolve(hostname, record)
            for rdata in answers:
                result.append(rdata.to_text())
    except Exception as e:
        infomsg("exception "+str(e))
    return result

async def doemailblacklistscall(protocol,hostname,ignorelist,tolerance,proxy):
    try:
        ips = resolverecord(protocol,hostname)
        if len(ips)==0:
            exitnagios("CRITICAL","cannot resolve "+hostname+" with protocol "+protocol)
        if len(ips)>1:
            exitnagios("CRITICAL","too many ips resolved for "+hostname+" - "+str(ips))
        targetip = ips[0]
        infomsg("The IP to test is "+targetip)

        driver = await generatedriver(proxy)

        # OTHER ALTERNATIVES
        #https://mxtoolbox.com/SuperTool.aspx?action=blacklist
        #https://www.dnsbl.info/dnsbl-database-check.php
        #https://blacklistchecker.com/check
        #https://www.uceprotect.net/en/rblcheck.php

        # OTHER OPTION
        # https://manpages.debian.org/bookworm/amispammer/amispammer.1.en.html -- perl code gives warnings, and fails with IPv6

        infomsg("browser OK")

        #driver.get("https://www.whatismybrowser.com/detect/what-is-my-user-agent/")
        #detected_user_agent = driver.find_element(By.ID, "detected_value").text
        #infomsg(f"Detected User Agent: {detected_user_agent}")

        targeturl = "https://dnschecker.org/ip-blacklist-checker.php"
        infomsg("asking for navigating "+targeturl)
        page = await driver.get(targeturl)
        #page = page.main_tab

        infomsg("manual delay")
        time.sleep(2)

        await wait_page_loaded(page)
        infomsg("page loaded")

        #currenturl = driver.current_url
        #driver.get("the current page is "+currenturl)

        #sourceraw = await page.send(uc.cdp.dom.get_outer_html())
        sourceraw = await get_html_source(page)
        if (sourceraw == None) or (sourceraw.strip() == ""):
            infomsg("The page source is empty")
        else:
            infomsg("The page source has contents")
            pagetitle = await get_page_title(page)
            infomsg("The page title is '"+str(pagetitle)+"'")
            if (pagetitle in ["New tab","",None]) or ("Access denied" in pagetitle) or ("Cloudflare" in pagetitle):
                infomsg("Aborting...")
                infomsg(sourceraw)
                exitnagios("CRITICAL","could not get effective page, maybe antibot protection")
            else:
                infomsg("page OK")
                infomsg(sourceraw)

        infomsg("waiting for mTools")
        await page.wait_for("#mTools", timeout=20)

        infomsg("waiting for ipbc_submit")
        await page.wait_for("#ipbc_submit", timeout=20)

        infomsg("finding textbox element")
        elements = tryfindbyid(driver,"ipbc_host")
        if len(elements)==0:
            exitnagios("CRITICAL","cannot find textbox")
        else:
            infomsg("sending ip")
            elements[0].send_keys(targetip)
            elements[0].send_keys(Keys.RETURN)

        infomsg("manual delay")
        time.sleep(10)

        infomsg("waiting for result")
        wait.until(EC.presence_of_element_located((By.ID, "blacklist_count")))

        infomsg("extracting listed")
        blocks = tryfindbyid(driver,"ipbc_results_dnsbl")
        lists = tryfindbytagname(blocks[0],"tr")
        infomsg("row canidates: "+str(len(lists)))
        issues=[]
        for item in lists:
            providers = tryfindbytagname(item,"th")
            if len(providers)==1:
                provider = providers[0].text
            else:
                provider = ""
            statuses = tryfindbytagname(item,"td")
            if len(statuses)==2:
                listed = statuses[0].text.split()[0]
            else:
                listed = ""
            if provider!="" and listed!="":
                infomsg("status "+provider+" "+listed)
                if listed.lower()=="yes":
                    if provider in ignorelist:
                        infomsg("ignoring "+provider)
                    else:
                        infomsg("adding "+provider)
                        issues.append(provider)

        if len(issues)>tolerance:
            exitnagios("CRITICAL","The IP "+targetip+" is listed in spam databases "+str(issues)+" | count="+str(len(issues)))
        elif len(issues)>0:
            exitnagios("WARNING","The IP "+targetip+" is listed in spam databases "+str(issues)+" | count="+str(len(issues)))
        else:
            exitnagios("OK","No issues found for the IP "+targetip+" | count="+str(len(issues)))

    except Exception as e:
        exitnagios("CRITICAL","unexpected error during the check "+str(e))
        infomsg(driver.page_source)

#-------------------------------------------------------------------------------

async def main(forcedargs=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("-4", "--ipv4",              action="store_true",  dest="ipv4",             default=False,                                help="use ipv4 (exclusive with ipv6)")
    parser.add_argument("-6", "--ipv6",              action="store_true",  dest="ipv6",             default=False,                                help="use ipv6 (exclusive with ipv4)")
    parser.add_argument("-0", "--ipv0",              action="store_true",  dest="ipv0",             default=False,                                help="do not specify ip protocol version")
    parser.add_argument("-H", "--hostname",                                dest="hostname",                                                       help="server to check")
    parser.add_argument("-i", "--ignore",                                  dest="ignore",           default="",                                   help="lists to ignore")
    parser.add_argument("-l", "--tolerance",                               dest="tolerance",        default="0",                                  help="number of listed databases to tolerate")
    parser.add_argument("-®", "--debug",             action="store_true",  dest="debug",            default=False,                                help="be more verbose")
    args = parser.parse_args(forcedargs)

    setcandebug(args.debug)

    protocol = None
    exclist = 0
    if args.ipv0 == True :
        protocol = ""
        exclist = exclist+1
    if args.ipv4 == True :
        protocol = "-4"
        exclist = exclist+1
    if args.ipv6 == True :
        protocol = "-6"
        exclist = exclist+1
    if (exclist>1) :
        exitnagios("CRITICAL","select ip protocol version 4 or 6, or 0 to relay on OS handling")
    elif (exclist<1) :
        exitnagios("CRITICAL","no protocol selected")

    if (args.hostname == ""):
        exitnagios("CRITICAL","hostname not defined")

    proxy = ""
    ignorelist = args.ignore.split(",")
    tolerance = int(args.tolerance)
    await doemailblacklistscall(protocol,args.hostname,ignorelist,tolerance,proxy)

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    asyncio.run(main())

#-------------------------------------------------------------------------------
